server:
  port: 8083

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: 1234
#    driver-class-name: oracle.jdbc.driver.OracleDriver
##    url: jdbc:oracle:thin:167.179.68.27:1521/GGSYS
#    url: jdbc:oracle:thin:@167.179.68.27:1521:ORCL
#    username: system
#    password: aoacdty56
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/